---
title: "Thoughts on R"
author: "Damon D'Ambrosio"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Thoughts on using R for data science- current and moving forward

I have gained a newfound respect for R through this course, and have come to prefer working with it over SAS. It is an incredibly powerful tool, and the things we have learned (e.g., RMarkdown) have assuaged my concerns with things such as reproducibility. I would like to continue using R moving forward, but that largely depends on my job. In my current role, we have to do data analyses that are submitted to regulatory agencies around the world. Because of this, SAS is generally preferred, as none of its features ever deprecate, and we can be reasonably confident that a SAS program and associated dataset we produce will produce an identical output for a regulator halfway around the world running the program on their machine at any point in the future. Further, these analyses are on data from designed experiments, and generally do not have extraordinarily large datasets that need EDA or any other activities that play to the strengths of R. With that being said, I will be changing roles and will no longer have to worry about dealing with outside regulatory agencies with analyses; analysis and conclusions will stay in house. I see the potential to use R and many of the things we have learned in this capacity. I also like the free and open-source nature of R; I do not have to worry about pesky things like SAS licenses if I ever had the desire to practice things on my own.

## Things I will do differently

Prior to this course, I was not a good R programmer. My environments were always a disorganized mess, I did not employ useful features like Projects, and had no concept of RMarkdown. I also did not know about the `Tidyverse` in general; I knew of `ggplot2`, but my old bits of `ggplot2` code definitely reflect a lack of understanding of exactly how it worked. Because of this, SAS, with everything centralized in one program script, always felt more comfortable. This course has taught me to stay organized, and through that, I realized that most of my "issues" with R stemmed from my lack of understanding of both how to keep R-related things organized, and how exactly R worked. I am excited at the prospect of keeping this newfound organizational ability moving forward, and am excited to see how I can incorporate R into future analytical tasks in my career. I also like the idea of using a notebooking approach with RMarkdown to ensure future reproducibility; one advantage I always thought SAS had was that it was easy to look at a program and figure out what I did in the past; through RMarkdown, I can now do this better in R.

## What areas of statistics/data science I will explore further

It was very interesting to learn about "machine learning." Prior to this course, I had heard of the concept, but it seemed like more of a buzzword instead of something useful. I now know that this is not the case. While I am not entirely sure what utility machine learning will have for my career in the future, I really like the idea of the various ensemble model approaches, and am personally curious to explore these further if the opportunity presents itself. Again, I am currently in a role where more "familiar" traditional mixed-models on data from designed experiments are expected. My future role may cause this to change, however. I will definitely be looking for ways to incorporate some of these ensemble model approaches into my work once I make the role transition.

Overall, I enjoyed this course very much, and am excited to try and find ways to apply what I have learned.